name: diversecity
favicon: null
layout_spectrum: 0.3649128838442266
typography_spectrum: 0.38542955997399986
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2545995330438018
  lightness: 0.41595021612010896
  saturation: 0.45618570037186146
  rhythmicContrast: 0.9813757119700313
purpose: []
