name: diversecity
favicon: null
layout_spectrum: 0.3649128838442266
typography_spectrum: 0.38542955997399986
title: DiverseCity Community Partnership
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6b6c67'
    - '#91908e'
    - '#623100'
    - '#fffeff'
    - '#bdc6c3'
  brandStrength: 0.4375
  lightness: 0.8125
  saturation: 0.45618570037186146
  rhythmicContrast: 0.9813757119700313
purpose: []
